//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Content
    {

        public int Content_ID { get; set; }
        public int ContentArea_ID { get; set; }
        public string Description { get; set; }
        public string ContentValue { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Publish_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public bool Active { get; set; }
    }
}
