//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.ModelConfiguration.Conventions;



    public partial class Entities : DbContext
    {
        public Entities(string ConnectionString )
            : base(ConnectionString)
        {
           
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Content>().HasKey(t => t.Content_ID);
            modelBuilder.Entity<ContentArea>().HasKey(t => t.ContentArea_ID);
            modelBuilder.Entity<Navigation_Items>().HasKey(t => t.Navigation_Item_ID);
            modelBuilder.Entity<Navigation_Types>().HasKey(t => t.Navigation_Type_ID);
            modelBuilder.Entity<NavigationItem_ResourceRole_Xref>().HasKey(t => t.Navigation_Role_Xref_ID);
            modelBuilder.Entity<Resource>().HasKey(t => t.Resource_ID);
            modelBuilder.Entity<Resource_Roles>().HasKey(t => t.Resource_Role_ID);
            modelBuilder.Entity<User>().HasKey(t => t.User_ID);
            modelBuilder.Entity<User_Role_Xref>().HasKey(t=> new { t.Resource_Role_ID, t.User_ID }  );
            modelBuilder.Entity<WebSession>().HasKey(t => t.WebSessionID);
            modelBuilder.Entity<WebSessionInformation>().HasKey(t => t.WebSessionInformationID);

            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();


        }

       
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentArea> ContentAreas { get; set; }
        public virtual DbSet<Navigation_Items> Navigation_Items { get; set; }
        public virtual DbSet<Navigation_Types> Navigation_Types { get; set; }
        public virtual DbSet<NavigationItem_ResourceRole_Xref> NavigationItem_ResourceRole_Xref { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Resource_Roles> Resource_Roles { get; set; }
        public virtual DbSet<User_Role_Xref> User_Role_Xref { get; set; }
        public virtual DbSet<User> Users { get; set; }
      
        public virtual DbSet<WebSessionInformation> WebSessionInformations { get; set; }
        public virtual DbSet<WebSession> WebSessions { get; set; }
    }

    class User_Role_Xref_Configuration : EntityTypeConfiguration<User_Role_Xref>
    {
        public User_Role_Xref_Configuration()
        {
            HasKey(t => t.Resource_Role_ID);
            HasKey(t => t.User_ID);
        }
    }

}
