//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation_Items
    {
        public int Navigation_Item_ID { get; set; }
        public string Navigation_Item_Caption { get; set; }
        public string Navigation_Item_Image { get; set; }
        public string Navigation_Item_URI { get; set; }
        public Nullable<int> Parent_Navigation_Item_ID { get; set; }
        public int Navigation_Item_Level_Sort_Order { get; set; }
        public int Navigation_Type_ID { get; set; }
        public string Navigation_Item_URI_Target { get; set; }
        public Nullable<bool> Navigation_Item_TreeView_Visible { get; set; }
        public Nullable<bool> Navigation_Item_Menu_Visible { get; set; }
        public string Navigation_Item_SiteMap_Caption { get; set; }
    }
}
