//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationItem_ResourceRole_Xref
    {
        public int Resource_Role_ID { get; set; }
        public int Navigation_Item_ID { get; set; }
        public int Navigation_Role_Xref_ID { get; set; }
    }
}
