//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Roles
    {
        public int Resource_Role_ID { get; set; }
        public int Resource_ID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Description { get; set; }
    }
}
