//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monacos.us.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSessionInformation
    {
        public int WebSessionInformationID { get; set; }
        public int WebSessionID { get; set; }
        public string WebSessionServerVariableName { get; set; }
        public string WebSessionServerVariableValue { get; set; }
        public Nullable<System.DateTime> Entry_DateTime { get; set; }
    }
}
